### ISSUE TITLE
Use `pytest` instead of `unittest`

### ISSUE THREAD

**Issue by julianghionoiu** [julianghionoiu/tdl-runner-python#4]
Both code and documentation needs to be updated

**Comment by neomatrix369** [comment]
Same question here. change the requirements file to make pytest available?

**Comment by neomatrix369** [comment]
I think the test source files will need to be changed as well

**Comment by neomatrix369** [comment]
My other question is will this affect the code coverage aspects of the workflow?

**Comment by neomatrix369** [comment]
I have managed to fix the above issue, see PR at https://github.com/julianghionoiu/dpnt-coverage/pull/30, although its WIP, since https://github.com/julianghionoiu/tdl-runner-python/pull/5 needs to first work before we can say https://github.com/julianghionoiu/dpnt-coverage/pull/30 is good

**Comment by neomatrix369** [comment]
I have checked mark all items mentioned here https://github.com/julianghionoiu/tdl-runner-python/issues/4#issuecomment-446487930

**Comment by neomatrix369** [comment]
Closing this issue due to completion of https://github.com/julianghionoiu/tdl-runner-python/pull/5
